schema_id: random_schema_id
name: aws_assume_role
sync_mode: MANUAL
sync_options:
    github:
        url: GJ-playgroud/managed-repository-resources/aws/schema.yaml
schema: 
    name: hogehoge
labels:
    - label_1
    - label_2
tags:
    key: value
